version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: frontend-base
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - ./packages/common:/app/packages/common
      - /app/node_modules
      - /app/apps/frontend/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - preloved-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: backend-base
    ports:
      - "8000:8000"
    volumes:
      - ./apps/backend:/app/backend
      - backend-venv:/app/backend/.venv
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./preloved_corner.db
      - ALLOWED_HOSTS=["http://localhost:3000", "http://127.0.0.1:3000"]
    networks:
      - preloved-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  backend-venv:

networks:
  preloved-network:
    driver: bridge